
export const CREATE_COMMENT_REQUEST='CREATE_COMMENT_REQUEST'
export const CREATE_COMMENT_SUCCESS='SUCCESS_COMMENT_REQUEST'
export const CREATE_COMMENT_FAILURE='FAILURE_COMMENT_REQUEST'

export const DELETE_COMMENT_REQUEST='DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS='DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_FAILURE='DELETE_COMMENT_REQUEST'

export const FETCH_COMMENT_REQUEST='FETCH_COMMENT_REQUEST'
export const FETCH_COMMENT_SUCCESS='FETCH_COMMENT_REQUEST'
export const FETCH_COMMENT_FAILURE='FETCH_COMMENT_REQUEST'
