export const FETCH_MESSAGES_REQUEST='FETCH_MESSAGES_REQUEST'
export const FETCH_MESSAGES_SUSSES='FETCH_MESSAGES_SUSSES'
export const FETCH_MESSAGES_FAILUE='FETCH_MESSAGES_FAILUE'

export const SEND_MESSAGES_REQUEST='SEND_MESSAGES_REQUEST'
export const SEND_MESSAGES_SUSSES='SEND_MESSAGES_SUSSES'
export const SEND_MESSAGES_FAILUE='SEND_MESSAGES_FAILUE'

export const FETCH_CHAT_BY_ID_PROJECT_REQUEST='FEATCH_CHAT_BY_ID_PROJECT_REQUEST'
export const FETCH_CHAT_BY_ID_PROJECT_SUSSESS='FEATCH_CHAT_BY_ID_PROJECT_SUSSESS'
export const FETCH_CHAT_BY_ID_PROJECT_FAILUE='FEATCH_CHAT_BY_ID_PROJECT_FAILUE'

export const FETCH_CHAT_MESSAGES_REQUEST = "FETCH_CHAT_MESSAGES_REQUEST";
export const FETCH_CHAT_MESSAGES_SUCCESS = "FETCH_CHAT_MESSAGES_SUCCESS";
export const FETCH_CHAT_MESSAGES_FAILURE = "FETCH_CHAT_MESSAGES_FAILURE";
